//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterNGOpart1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAFEntities : DbContext
    {
        public DAFEntities()
            : base("name=DAFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disaster> Disasters { get; set; }
        public virtual DbSet<Goods_Allocation> Goods_Allocation { get; set; }
        public virtual DbSet<Goods_Donations> Goods_Donations { get; set; }
        public virtual DbSet<Goods_Purchase> Goods_Purchase { get; set; }
        public virtual DbSet<Mon_Allocation> Mon_Allocation { get; set; }
        public virtual DbSet<Mon_Donation> Mon_Donation { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Register1> Registers1 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
