//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterNGOpart1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Allocation
    {
        public int GoodsAll_ID { get; set; }
        public Nullable<System.DateTime> GoodsAll_Date { get; set; }
        public Nullable<int> No_of_item { get; set; }
        public Nullable<int> Disaster_ID { get; set; }

        public virtual Disaster Disaster { get; set; }
        public virtual Goods_Donations GoodsDonations { get; set; }

        public int Id { get; set; }
        public int DisasterId { get; set; } // Foreign key to the Disaster
        public string DisasterName { get; set; } // type of disaster from the disaster table 
        public string Goods { get; set; }
        public int NumOfItems { get; set; }
    }
}
