//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterNGOpart1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Purchase
    {
        public int GoodsPur_ID { get; set; }
        public Nullable<decimal> GoodsPurch_Amt { get; set; }
        public Nullable<System.DateTime> GoodsPurch_Date { get; set; }
        public Nullable<int> No_of_items { get; set; }
        public Nullable<int> Disaster_ID { get; set; }
        public Nullable<int> Goods_ID { get; set; }

        public virtual Disaster Disaster { get; set; }
        public virtual Goods_Donations GoodsDonations { get; set; }

        public int Id { get; set; }
        public string GoodsName { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public int DisasterId { get; set; } // fk

    }
}
