//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterNGOpart1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mon_Allocation
    {
        public int MonAll_ID { get; set; }
        public Nullable<decimal> MonAll_Amt { get; set; }
        public Nullable<System.DateTime> MonAll_Date { get; set; }
        public int Disaster_ID { get; set; }

        public string Annonymous { get; set; }

        public virtual Disaster Disaster { get; set; }

        public int MoneyAllocationID { get; set; }
        public int DisasterId { get; set; } // Foreign key to the Disaster
        public decimal AllocatedAmount { get; set; }
    }
}
